name: Self-hosted Runner Examen

on:
  push:
    branches:
      - main

jobs:

  # Self runner
  self-hosted-job:

    runs-on:
      - self-hosted
      - windows
      - custom-runner

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
